ias_game_homepage:
    path:     /game
    defaults: { _controller: IasGameBundle:Default:index}


ias_game_get_game_session:
    path:     /inquiry
    defaults: { _controller: IasGameBundle:Default:getGame}

ias_game_example:
     path:     /example
     defaults: { _controller: IasGameBundle:Default:example}
