ias_game_homepage:
    path:     /game
    defaults: { _controller: IasGameBundle:Default:index}


ias_game_get_game_session:
    path:     /inquiry
    defaults: { _controller: IasGameBundle:Default:getGame}

ias_game_init_game_session:
    path:     /game/init
    defaults: {_controller: IasGameBundle:Play:initGameSession}

ias_game_join_game:
    path: /game/join/{id}
    defaults: {_controller: IasGameBundle:Play:joinGameSession}
    methods: [GET]
    requirements:
        id: '\d+'

ias_game_unjoin_game:
    path: /game/unjoin/{id}
    defaults: {_controller: IasGameBundle:Play:unjoinGameSession}
    methods: [GET]
    requirements:
        id: '\d+'

ias_game_play_game:
    path: /game/play/
    defaults: {_controller: IasGameBundle:Play:Play}


####Для дебага####
ias_game_example:
     path:     /example
     defaults: { _controller: IasGameBundle:Default:example}
