ias_game_homepage:
    path:     /game
    defaults: { _controller: IasGameBundle:Default:index}

ias_game_get_game:
    path:     /game/{id}
    defaults: { _controller: IasGameBundle:Default:getGame}
    requirements:
        id: '\d+'