ias_game_homepage:
    path:     /game
    defaults: { _controller: IasGameBundle:Default:index}

ias_game_get_game_session:
    path:     /inquiry
    defaults: { _controller: IasGameBundle:Default:getGame}

ias_game_is_game_session:
    path:     /game/isgame
    defaults: {_controller: IasGameBundle:Game:isStartGameSession, _format: json}
    methods: [POST]
    requirements:
        _format: json|csv


ias_game_init_game_session:
    path:     /game/init
    defaults: {_controller: IasGameBundle:Game:initGameSession}

ias_game_join_game:
    path: /game/join/{id}
    defaults: {_controller: IasGameBundle:Game:joinGameSession}
    methods: [GET]
    requirements:
        id: '\d+'

ias_game_unjoin_game:
    path: /game/unjoin/{id}
    defaults: {_controller: IasGameBundle:Game:unjoinGameSession}
    methods: [GET]
    requirements:
        id: '\d+'

ias_game_play_game:
    path: /game/play/
    defaults: {_controller: IasGameBundle:Game:Play}


####Для дебага####
ias_game_example:
     path:     /example
     defaults: { _controller: IasGameBundle:Default:example}
