services:
#    ias_game.example: Название
#        class: Ias\GameBundle\Example Путь к классу по PSR
#        arguments: ["@service_id", "plain_value", "%parameter%"] параметры конструктора

    game_session:
        class: Ias\GameBundle\Service\Game\GameSession
        factory: ['Ias\GameBundle\Service\Game\GameSession', getSession]
        arguments: ["@doctrine.orm.entity_manager"]

#    as.ias_game.play.play_game:
#        class: Ias\GameBundle\Service\Play\PlayGame\Game
#        arguments: ["%game_id%"]
