<?php

namespace Ias\GameBundle\Repository;

/**
 * GamerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamerRepository extends \Doctrine\ORM\EntityRepository
{
}
