<?php

namespace Ias\GameBundle\Repository;

use Ias\GameBundle\Entity\Game;
/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActiveGameSession()
    {

        $query = $this->getEntityManager()
            ->createQuery('SELECT p, c, d FROM IasGameBundle:Game p
                            JOIN p.gameSession c
                            JOIN c.gamer d
                            ORDER BY p.name');

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getAllGameInBase()
    {
        $db = $this->getEntityManager()->createQueryBuilder()->select('g')->from('IasGameBundle:Game', 'g');
        $request = $db->getQuery();
        
        try {
            return $request->execute();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
