<?php

namespace Ias\GameBundle\Repository;

/**
 * GamerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamerRepository extends \Doctrine\ORM\EntityRepository
{
    const TABLE = "IasGameBundle:Gamer";

    public function countSession($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('count(g.id) as num')
            ->from(self::TABLE, 'g')
            ->leftJoin('g.gameSession', 's')
            ->where('s.id = :id')
            ->setParameters(['id' => $id]);


        try {
            return $query->getQuery()->getResult()[0]['num'];
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function getGamersForSession($id)
    {
//        $query = $this->getEntityManager()->createQueryBuilder()
//            ->select('p.id')
//            ->from(self::TABLE, 'p')
//            ->leftJoin('p.gameSession', 's')
//            ->where('s.id = :id')
//            ->setParameters(['id' => $id]);

        $query = $this->getEntityManager()->createQuery("
            SELECT p.id FROM IasGameBundle:Gamer p
            LEFT JOIN p.gameSession c
            WHERE c.id = :id
        ")->setParameters(['id' => $id]);

        //а разницы нихера

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }

    }
}
