<?php

namespace Ias\GameBundle\Repository;

/**
 * PlaySessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaySessionRepository extends \Doctrine\ORM\EntityRepository
{
}
