<?php

namespace Ias\GameBundle\Repository;

/**
 * StorageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageRepository extends \Doctrine\ORM\EntityRepository
{
    const TABLE = "IasGameBundle:Storage";

    public function getGameStorage($id)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('s')
            ->from(self::TABLE,'s')
            ->leftJoin('s.game', 'g')
            ->leftJoin('g.gameSession', 'gs')
            ->where('gs.id = :id')
            ->setParameters(['id' => $id]);

        try {
            return $query->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
